baseURL = "https://psyduck.ru/"
title = "Psyduck's comfy place."
theme = "hugo-nederburg-theme"
languageCode = "ru-RU"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Welcome to my blog of thoughts, my dear fiend!"
  description = "Добро пожаловать в мой блог обо всем подряд!" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Psyduck"
  authorLink = "http://psyduck.ru/"
  bio = [
    "Меня зовут Алексей, я люблю всего понемножку и побольше!"
  ]
  copyright = [
    "&copy; 2020 Psyduck",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
    "A port of Tracks by Compete Themes."
  ]

  disable_sri = true

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "talversound@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Books"
  url = "categories/books/"
  weight = 2

  [[menu.main]]
  name = "Music"
  url = "music/"
  weight = 3

  [[menu.main]]
  name = "Games"
  url = "categories/games/"
  weight = 4

  [[menu.main]]
  name = "Stuff"
  url = "categories/stuff/"
  weight = 5

  [[menu.main]]
  name = "Read me"
  url = "about/"
  weight = 6

  [[menu.main]]
  name = "Write me"
  url = "contact/"
  weight = 7

# this will also be in author bio if there is no writer.
  [params.social]
  email         = "talversound@gmail.com"
  instagram     = "https://www.instagram.com/talver_sound/"
  # github        = "https://github.com/Ypsckud"
  # facebook      = "full Social profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # pinterest     = "full profile url in pinterest"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]

  # [params.writers."Göran Svensson"]
  #  link = "https://appernetic.io/"
  #  email = "goran@molnsys.com"
  #  bio = [
  #    "Göran is an avid blogger and the founder of <a href='https://appernetic.io/'>Appernetic.io</a>. This is the author bio shown after posts."
  #  ]
  #  facebook      = "full Göran profile url in facebook"
  #  googleplus    = "full profile url in googleplus"
  #  twitter       = "full profile url in twitter"
  #  linkedin      = "full profile url in linkedin"
  #  stackoverflow = "full profile url in stackoverflow"
  #  instagram     = "full profile url in instagram"
  #  github        = "full profile url in github"
  #  pinterest     = "full profile url in pinterest"
